feat: refactor, add ts and wasm
ideal-lab5/timelock pull request #1
Opened 2024-11-14 16:20 UTC by driemworks

2024-11-15 10:19 UTC, juangirini requested changes
I know that many of the requested changes come inherited from the source repo. But we need to clean up.
In general, we can't merge commented out code to the main branch.
There are still mentions to ETF everywhere.

There are also more things to do but I reckon they should be done as separate [issues](https://github.com/ideal-lab5/tle/issues), these are:
- code formatting
- use mocks in the tests
- update the RPCs urls

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.test.spec.ts
> +    }));
why this is not in a loop?

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.test.spec.ts
> +    await etf.init()
```suggestion
    const tle = new Tle('wss://example.com', true);
    await tle.init()
```

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.test.spec.ts
> +    etf.getPulse(0).then(pulse => {
```suggestion
    tle.getPulse(0).then(pulse => {
```

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.test.spec.ts
> +    await etf.timelockEncrypt(new TextEncoder().encode(message), latestBlockNumber, seed).then((result) => {
```suggestion
    const tle = new Tle()
    await tle.init(JSON.stringify(chainSpec), false)
    const seed = 'seed';
    const latestBlockNumber = 123;
    const message = 'Hello, world!'
    await tle.timelockEncrypt(new TextEncoder().encode(message), latestBlockNumber, seed).then((result) => {
```

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.test.spec.ts
> +        etf_ct: 'mocked-etf-ct',
is this correct? or should it be `tle_ct`?

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.test.spec.ts
> +    const result = await etf.timelockDecrypt(ciphertext, blockNumber);
```suggestion
    const tle = new Tle()
    await tle.init(JSON.stringify(chainSpec), false)
    const blockNumber = 1;
    const ciphertext = 'ciphertext'
    const result = await tle.timelockDecrypt(ciphertext, blockNumber);
```

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.test.spec.ts
> +    await etf.init(JSON.stringify(chainSpec), false)
```suggestion
    const tle = new Tle()
    await tle.init(JSON.stringify(chainSpec), false)
```

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.ts
> +// This class initializes the ETF.js SDK
```suggestion
// Timelock Encryption
// This class initializes the tle.js SDK
```

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.ts
> +export class Etf {
```suggestion
 * Timelock Encryption
 * This class initializes the tle.js SDK
 */
export class Tle {
```

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.ts
> +   * Constructor for the etf api
```suggestion
   * Constructor for the tle api
```

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.ts
> +   *      secure websocket (rpc): wss://etf1.idealabs.network:443
This will need an update https://github.com/ideal-lab5/tle/issues/2

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.ts
> +   * @param chainSpec The ETF Network (raw) chain spec
```suggestion
   * Connect to the chain and start tle api wrapper
   * @param chainSpec The Ideal Network (raw) chain spec
```

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.ts
> +    this.ibePubkey = await this.api.query.etf.roundPublic()
This will need an update

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.ts
> +    this.api.rpc.beefy.subscribeJustifications((sig) => {
Is this the real beefy or the beefy-etf?

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.ts
> +    // let validatorSetId = blockNumber % epochLength;
```suggestion
```

2024-11-15 10:19 UTC, juangirini commented on ts/src/tle.ts
> +      // let encodedMessage = message;
```suggestion
```

2024-11-15 10:19 UTC, juangirini commented on wasm/src/lib.rs
> +/// in etf-crypto-primitives
does it still hold that name

2024-11-15 10:19 UTC, juangirini commented on wasm/src/lib.rs
> +/// in etf-crypto-primitives
same here

2024-11-15 10:19 UTC, juangirini commented on wasm/src/lib.rs
> +	// let sig_value = sig_conversion.get(0).unwrap();
```suggestion
```

2024-11-15 10:19 UTC, juangirini commented on wasm/src/lib.rs
> +	// failed"))?;
```suggestion
```

2024-11-15 10:19 UTC, juangirini commented on wasm/src/lib.rs
> +
```suggestion
```

2024-11-15 10:19 UTC, juangirini commented on wasm/src/lib.rs
> +			// sig_vec.serialize_compressed(&mut sig_bytes).unwrap();
```suggestion
```

2024-11-15 14:24 UTC, driemworks commented
> I know that many of the requested changes come inherited from the source repo. But we need to clean up.
> 
>     * Generally, we can't merge commented-out code to the main branch.
> 
>     * There are still mentions of ETF everywhere.
> 
>     * Some nits, like using capital letters to start docs comments, or add descriptions to todos
> 
> 
> There are also more things to do but I reckon they should be done as separate [issues](https://github.com/ideal-lab5/tle/issues), these are:
> 
>     * code formatting
the same rustfmt.toml from the murmur crate is used here, except I shortened line lengths to 80 instead of 100, can change it back if you prefer but I like the shorter lines more. 

>     * use mocks in the tests
What tests require mocks?

>     * update the RPCs urls
- which rpcs? there aren't any here, I think this comment may have been for a diff repo?

2024-11-15 15:07 UTC, driemworks commented on tle/src/stream_ciphers.rs
> +		// TODO:get a valid nonce size as a constant
no, it just needs to replace 12 with a const, will include in the next commit

2024-11-15 15:42 UTC, driemworks commented
>     * Generally, we can't merge commented-out code to the main branch.

we should implement a process that enforces this.
 
>     * There are still mentions of ETF everywhere.
The majority of these mentions are in the copied TS wrapper (etf.js). I removed references in the core/wasm libs but created a new issue to address etf.js (and migrate it to tle.js or whichever name we land on: https://github.com/ideal-lab5/tle/issues/6

2024-11-15 16:20 UTC, driemworks commented on tle/Cargo.toml
> +name = "tle"
maybe `timelock`, `timelock-rs`, or `tlock-rs`? none of those are used yet

2024-11-15 17:08 UTC, driemworks commented on ts/README.md
> +await etf.init(chainSpec)
will update this as part of #6

2024-11-15 17:08 UTC, driemworks commented on ts/README.md
> +Delayed transactions can be submitted by  using the `etf.delay` API.
#6

2024-11-15 17:08 UTC, driemworks commented on ts/README.md
> +let innerCall = etf.api.tx.balances
#6

2024-11-19 09:47 UTC, juangirini requested changes
I started reviewing it and got bored of code clean-up comments.
This needs some "search and replace" `tle`-> `timelock`, 'etf` -> `timelock`, `ETF Network` -> `Ideal Network`. File renaming, probably? Removing commented-out code.

2024-11-19 09:47 UTC, juangirini commented on timelock/src/stream_ciphers.rs
> +/// Errors that mayb be encountered with using a stream cipher
```suggestion
/// Errors that may be encountered with using a stream cipher
```

2024-11-19 09:47 UTC, juangirini commented on ts/src/index.js
> +export * from './tle';
```suggestion
export * from './timelock';
```

2024-11-19 09:47 UTC, juangirini commented on ts/package.json
>    "repository": "https://github.com/ideal-lab5/tle",
```suggestion
  "repository": "https://github.com/ideal-lab5/timelock",
```

2024-11-19 09:47 UTC, juangirini commented on ts/src/tle.js
Shouldn't this file be renamed to `timelock`?

2024-11-19 09:47 UTC, juangirini commented on ts/src/tle.js
> +    // https://github.com/ideal-lab5/tle/issues/7
```suggestion
    // https://github.com/ideal-lab5/timelock/issues/7
```

2024-11-19 09:47 UTC, juangirini commented on ts/src/tle.test.spec.js
> +import { timelockEncrypt, IdealNetworkIdentityHandler } from './tle';
```suggestion
import { timelockEncrypt, IdealNetworkIdentityHandler } from './timelock';
```

2024-11-19 09:47 UTC, juangirini commented on ts/src/tle.test.spec.js
> +    // })
```suggestion
```

2024-11-19 22:41 UTC, driemworks commented
Closing in place of simpler PR that only impacts the rust components, will address typescript wrapper in a new PR as well, tracked in https://github.com/ideal-lab5/timelock/issues/9 and https://github.com/ideal-lab5/timelock/issues/6

2024-11-19 22:42 UTC, driemworks commented
Closing in place of simpler PR that only impacts the rust components, will address typescript wrapper in a new PR as well, tracked in https://github.com/ideal-lab5/timelock/issues/9 and https://github.com/ideal-lab5/timelock/issues/6

2024-11-19 22:42 UTC, closed without merging